dependencies {
    implementation project(":minecraft-common")

    compileOnlyApi project(":core")
    compileOnlyApi project(":minecraft-bukkit:loader")
    compileOnlyApi project(":minecraft-paper")

    compileOnlyApi "net.flectone:libby-core:$libby_version"
    compileOnlyApi "org.incendo:cloud-paper:$cloud_paper_version"
    compileOnlyApi "com.github.retrooper:packetevents-spigot:$packetevents_spigot_version"
    compileOnlyApi "com.github.Anon8281:UniversalScheduler:$UniversalScheduler_version"

    // integrations
    compileOnly "org.spigotmc:spigot-api:$spigot_version"
    compileOnly "com.mojang:authlib:$mojang_authlib_version"
    compileOnly "de.maxhenkel.voicechat:voicechat-api:$voicechatapi_version"
    compileOnly "me.clip:placeholderapi:$placeholderapi_version"
    compileOnly "com.github.MilkBowl:VaultAPI:$vaultapi_version"
    compileOnly "com.github.LeonMangler:SuperVanish:$supervanishapi_version"
    compileOnly "com.loohp:InteractiveChat:$interactivechatapi_version"
    compileOnly "com.rexcantor64.triton:triton-api:$tritonapi_version"
    compileOnly "com.gitlab.ruany:LiteBansAPI:$litebans_version"
    compileOnly "com.github.DevLeoko:AdvancedBan:$advancedban_version"
    compileOnly "space.arim.libertybans:bans-api:$libertybans_version"
    compileOnly "dev.lone:api-itemsadder:$itemsadder_version"
    compileOnly "eu.kennytv.maintenance:maintenance-api:$maintenance_version"
    compileOnly "com.github.Zrips:CMI-API:$cmi_api_version"
}

shadowJar {
    relocate("com.github.Anon8281", "${relocated_pattern}.universalscheduler")
}

tasks.register("jarInJarContent", Jar) {
    archiveFileName = "flectonepulse-bukkit.jarinjar"

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from { zipTree(project(":minecraft-bukkit").tasks.named("shadeDowngradedApi").get().archiveFile) }
    from { zipTree(project(":minecraft-paper").tasks.named("shadeDowngradedApi").get().archiveFile) }
    from { zipTree(project(":minecraft-velocity").tasks.named("shadeDowngradedApi").get().archiveFile) }
    from { zipTree(project(":minecraft-bungeecord").tasks.named("shadeDowngradedApi").get().archiveFile) }

    dependsOn(":minecraft-bukkit:shadeDowngradedApi")
    dependsOn(":minecraft-paper:shadeDowngradedApi")
    dependsOn(":minecraft-velocity:shadeDowngradedApi")
    dependsOn(":minecraft-bungeecord:shadeDowngradedApi")
}

tasks.named("buildFinalJar", Jar) {
    archiveFileName = "FlectonePulse-Bukkit-" + project_version + ".jar"

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from { zipTree(project(":minecraft-bukkit:loader").tasks.shadowJar.archiveFile) }
    from { zipTree(project(":minecraft-velocity:loader").tasks.named("shadeDowngradedApi").get().archiveFile) }
    from { zipTree(project(":minecraft-bungeecord:loader").tasks.named("shadeDowngradedApi").get().archiveFile) }

    dependsOn(":minecraft-bukkit:loader:shadowJar")
    dependsOn(":minecraft-velocity:shadeDowngradedApi")
    dependsOn(":minecraft-bungeecord:shadeDowngradedApi")
}