dependencies {
    implementation project(":common")

    compileOnly project(":hytale:loader")
    compileOnly project(":api")

    compileOnly libraries.platform
    compileOnly libraries.adventure

    compileOnly "eu.mikart.adventure:adventure-platform-hytale:$adventure_platform_hytale_version"
    compileOnly "curse.maven:hyui-1431415:$hyui_version"
    compileOnly "com.hypixel.hytale:Server:$hytale_server_version"
    compileOnly "at.helpch:placeholderapi-hytale:$placeholderapi_hytale_version"
}

shadowJar {
    archiveFileName = "flectonepulse-hytale.jarinjar"
}

tasks.named("buildFinalJar", Jar) {
    archiveFileName = "FlectonePulse-Hytale-" + project_version + ".jar"

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from { zipTree(project(":hytale:loader").tasks.shadowJar.archiveFile) }

    dependsOn(":hytale:loader:shadowJar")
}