dependencies {
    implementation project(":core")

    compileOnlyApi project(":hytale:loader")

    compileOnlyApi "net.flectone:libby-core:$libby_version"
    compileOnlyApi "org.incendo:cloud-core:$cloud_core_version"
    compileOnlyApi "eu.mikart.adventure:adventure-platform-hytale:$adventure_platform_hytale_version"
    compileOnlyApi "curse.maven:hyui-1431415:$hyui_version"

    compileOnly "com.hypixel.hytale:Server:$hytale_server_version"
    compileOnly "org.apache.logging.log4j:log4j-core:$apache_logging_log4j_version"
    compileOnly "at.helpch:placeholderapi-hytale:$placeholderapi_hytale_version"
}

shadowJar {
    archiveFileName = "flectonepulse-hytale.jarinjar"
}

tasks.named("buildFinalJar", Jar) {
    archiveFileName = "FlectonePulse-Hytale-" + project_version + ".jar"

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from { zipTree(project(":hytale:loader").tasks.shadowJar.archiveFile) }

    dependsOn(":hytale:loader:shadowJar")
}