plugins {
    id "net.neoforged.moddev" version "${neoforge_moddev_version}"
}

neoForge {
    version = "${neoforge_version}"
}

configurations.configureEach {
    resolutionStrategy {
        force "org.jspecify:jspecify:1.0.1"
        force "it.unimi.dsi:fastutil:8.5.19"
        force "commons-io:commons-io:2.22.0"
    }
}

configurations {
    shadow
    implementation.extendsFrom shadow
}

dependencies {
    compileOnly project(":minecraft-neoforge:loader")
    compileOnly "org.incendo:cloud-neoforge:${cloud_neoforge_version}"

    shadow project(":core")
    shadow project(":minecraft-common")
    shadow files("libs/packetevents-neoforge-2.13.0.jar")
}

shadowJar {
    archiveFileName = "flectonepulse-neoforge.jarinjar"
    configurations = [project.configurations.shadow]
    minimize()
}

tasks.named("buildFinalJar", Jar) {
    archiveFileName = "FlectonePulse-NeoForge-" + project_version + ".jar"

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from { zipTree(project(":minecraft-neoforge:loader").tasks.shadowJar.archiveFile) }

    dependsOn(":minecraft-neoforge:loader:shadowJar")
}