plugins {
    id "net.neoforged.moddev" version "${neoforge_moddev_version}"
}

neoForge {
    version = "${neoforge_version}"
}

configurations.configureEach {
    exclude group: "com.github.retrooper", module: "adventure-text-serializer-gson"
    exclude group: "com.github.retrooper", module: "adventure-text-serializer-legacy"
    resolutionStrategy {
        force "org.jspecify:jspecify:1.0.1"
        force "commons-io:commons-io:2.22.0"
        force "org.apache.logging.log4j:log4j-core:2.26.1"
        force "org.apache.logging.log4j:log4j-api:2.26.1"
    }
}

configurations {
    shadow
    implementation.extendsFrom shadow
}

dependencies {
    shadow project(":common")
    shadow project(":minecraft-common")

    compileOnly project(":api")
    compileOnly project(":minecraft-neoforge:loader")

    compileOnly libraries.platform
    compileOnly libraries.adventure

    compileOnly "org.incendo:cloud-neoforge:${cloud_neoforge_version}"

    compileOnly "net.flectone:packeteventsmodern-api:$packetevents_spigot_version"
    compileOnly "net.flectone:packeteventsmodern-netty-common:$packetevents_spigot_version"
    compileOnly "net.flectone:packeteventsmodern-neoforge:$packetevents_spigot_version"
}

shadowJar {
    archiveFileName = "flectonepulse-neoforge.jarinjar"
    configurations = [project.configurations.shadow]
}

tasks.named("buildFinalJar", Jar) {
    archiveFileName = "FlectonePulse-NeoForge-" + project_version + ".jar"

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from { zipTree(project(":minecraft-neoforge:loader").tasks.shadowJar.archiveFile) }

    dependsOn(":minecraft-neoforge:loader:shadowJar")
}