package net.flectone.pulse.util.constant;

import java.util.Arrays;

public enum MessageType {
    AFK,
    ADVANCEMENT,
    AUTO,
    BED,
    BRAND,
    CHAT,
    CLEAR,
    CLONE,
    COMMAND_AFK,
    COMMAND_ANON,
    COMMAND_BALL,
    COMMAND_BAN,
    COMMAND_BANLIST,
    COMMAND_BROADCAST,
    COMMAND_CHATCOLOR,
    COMMAND_CHATSETTING,
    COMMAND_CLEARCHAT,
    COMMAND_CLEARMAIL,
    COMMAND_COIN,
    COMMAND_DELETE,
    COMMAND_DICE,
    COMMAND_DO,
    COMMAND_FLECTONEPULSE,
    COMMAND_GEOLOCATE,
    COMMAND_HELPER,
    COMMAND_IGNORE,
    COMMAND_IGNORELIST,
    COMMAND_KICK,
    COMMAND_MAIL,
    COMMAND_MAINTENANCE,
    COMMAND_ME,
    COMMAND_MUTE,
    COMMAND_MUTELIST,
    COMMAND_ONLINE,
    COMMAND_PING,
    COMMAND_POLL,
    COMMAND_REPLY,
    COMMAND_ROCKPAPERSCISSORS,
    COMMAND_SPY,
    COMMAND_STREAM,
    COMMAND_SYMBOL,
    COMMAND_TELL,
    COMMAND_TICTACTOE,
    COMMAND_TOPONLINE,
    COMMAND_TRANSLATETO,
    COMMAND_TRY,
    COMMAND_UNBAN,
    COMMAND_UNMUTE,
    COMMAND_UNWARN,
    COMMAND_WARN,
    COMMAND_WARNLIST,
    DAMAGE,
    DEATH,
    DELETE,
    DEOP,
    ENCHANT,
    ERROR,
    FOOTER,
    FORMAT,
    FROM_DISCORD_TO_MINECRAFT,
    FROM_TELEGRAM_TO_MINECRAFT,
    FROM_TWITCH_TO_MINECRAFT,
    GAMEMODE,
    GREETING,
    HEADER,
    JOIN,
    KILL,
    MENTION,
    MOTD,
    NAME,
    NEWBIE,
    OBJECTIVE,
    OP,
    PLAYERS,
    PLAYERLISTNAME,
    QUESTION_ANSWER,
    QUIT,
    REPLACEMENT,
    RIGHT_CLICK,
    SEED,
    SIDEBAR,
    SETBLOCK,
    SLEEP,
    SPAWN,
    SUMMON,
    SWEAR,
    TRANSLATE,
    UPDATE,
    VERSION,

    // only for invalidation cache
    SYSTEM_ONLINE,
    SYSTEM_OFFLINE,
    SYSTEM_BAN,
    SYSTEM_MUTE,
    SYSTEM_WARN;

    public String toProxyTag() {
        return "FlectonePulse:" + this.name();
    }

    public static MessageType fromProxyString(String string) {
        if (string == null || string.isEmpty()) return null;

        return Arrays.stream(MessageType.values())
                .filter(tag -> string.equals("FlectonePulse:" + tag.name()))
                .findAny()
                .orElse(null);
    }
}
