plugins {
    id 'net.neoforged.moddev' version "${neoforge_moddev_version}"
}

neoForge {
    version = "${neoforge_version}"
}

configurations.configureEach {
    resolutionStrategy {
        force 'org.jspecify:jspecify:1.0.1'
        force 'it.unimi.dsi:fastutil:8.5.19'
        force 'commons-io:commons-io:2.21.0'
    }
}

configurations {
    shade
    implementation.extendsFrom shade
}

dependencies {
    compileOnly("org.incendo:cloud-neoforge:${cloud_neoforge_version}")
    compileOnly(project(":minecraft:neoforge:loader"))

    // TODO: delete when neoforge repository appears
    shadow(files('libs/packetevents-neoforge-2.13.0.jar'))

    shadow(project(":core"))
    shadow(project(":minecraft:common"))
    shadow("net.flectone:libby-core:$libby_version")
}

shadowJar {
    archiveFileName = "flectonepulsedev-neoforge.jarinjar"
    configurations = [project.configurations.shadow]
    minimize()
}

processResources {
    def props = [version: "$project_version", author: "$project_author", description: "$project_description"]
    inputs.properties props
    filteringCharset 'UTF-8'
}

tasks.named("shadowJar") {
    configurations = [project.configurations.shadow]
}

artifacts {
    archives shadowJar
}

tasks.named("buildFinalJar", Jar) {
    from {
        zipTree(project(':minecraft:neoforge:loader').tasks.shadowJar.archiveFile)
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    dependsOn(':minecraft:neoforge:loader:shadowJar')
}