dependencies {
    compileOnly project(":api")
    compileOnly project(":minecraft-velocity:loader")

    compileOnly libraries.platform

    compileOnly "com.velocitypowered:velocity-api:$velocity_version"
    annotationProcessor "com.velocitypowered:velocity-api:$velocity_version"
}

shadowJar {
    archiveFileName = "flectonepulse-bukkit.jarinjar"
}

tasks.named("buildFinalJar", Jar) {
    from(zipTree(tasks.shadowJar.archiveFile))
    dependsOn tasks.shadowJar
}