plugins {
	id "net.fabricmc.fabric-loom" version "${fabric_loom_version}"
}

configurations {
	shadow
	implementation.extendsFrom shadow
}

dependencies {
	minecraft("com.mojang:minecraft:${fabric_minecraft_version}")

	shadow project(":common")
	shadow project(":minecraft-common")

	compileOnly project(":api")
	compileOnly project(":minecraft-fabric:loader")

	compileOnly libraries.platform
	compileOnly libraries.adventure

	compileOnly "net.fabricmc:fabric-loader:${fabric_loader_version}"

	compileOnly fabricApi.module("fabric-api-base", fabric_api_version)
	compileOnly fabricApi.module("fabric-command-api-v2", fabric_api_version)
	compileOnly fabricApi.module("fabric-lifecycle-events-v1", fabric_api_version)
	compileOnly fabricApi.module("fabric-networking-api-v1", fabric_api_version)

	compileOnly "org.incendo:cloud-fabric:${cloud_fabric_version}"
	compileOnly "com.github.retrooper:packetevents-fabric-official:$packetevents_spigot_version"

	// integrations
	compileOnly "eu.pb4:placeholder-api:$text_placeholder_api_version"
	compileOnly "maven.modrinth:vanish:$vanish_version"
	compileOnly "io.github.miniplaceholders:miniplaceholders-api:$miniplaceholders_api_version"
}

shadowJar {
	archiveFileName = "flectonepulse-fabric.jarinjar"
	configurations = [project.configurations.shadow]
}

tasks.named("buildFinalJar", Jar) {
	archiveFileName = "FlectonePulse-Fabric-" + project_version + ".jar"

	duplicatesStrategy = DuplicatesStrategy.EXCLUDE

	from { zipTree(project(":minecraft-fabric:loader").tasks.shadowJar.archiveFile) }

	dependsOn(":minecraft-fabric:loader:shadowJar")
}