dependencies {
    compileOnly project(":api")
    compileOnly project(":minecraft-bungeecord:loader")

    compileOnly libraries.platform

    compileOnly "net.md-5:bungeecord-api:$bungeecord_version"
}

shadowJar {
    archiveFileName = "flectonepulse-bukkit.jarinjar"
}

tasks.named("buildFinalJar", Jar) {
    from(zipTree(tasks.shadeDowngradedApi.archiveFile))
    dependsOn tasks.shadeDowngradedApi
}