dependencies {
    implementation project(":core")

    compileOnlyApi project(":minecraft-bungeecord:loader")

    compileOnly "net.md-5:bungeecord-api:$bungeecord_version"
}

shadowJar {
    archiveFileName = "flectonepulse-bukkit.jarinjar"
}

tasks.named("buildFinalJar", Jar) {
    from(zipTree(tasks.shadeDowngradedApi.archiveFile))
    dependsOn tasks.shadeDowngradedApi
}