package net.flectone.pulse.constant;

public enum HookType {

    CONFIGURE_SERIALIZATION,
    PRE_NEW_PLAYER_PLACE,
    ON_PLAYER_PRE_LOGIN,
    ON_PLAYER_LOGIN,
    POST_RESPAWN,
    INIT_PACKET_ADAPTER,
    TERMINATE_FAILED_PACKET_ADAPTER,
    TERMINATE_PACKET_ADAPTER,
    CLOSE_UIS,
    SIMPLEVOICE_ENTITY_SOUND_PACKET,
    SIMPLEVOICE_MICROPHONE_PACKET

}
