package net.flectone.pulse.util.constant;

public enum HookType {

    CONFIGURE_SERIALIZATION,
    PRE_NEW_PLAYER_PLACE,
    ON_PLAYER_PRE_LOGIN,
    ON_PLAYER_LOGIN,
    POST_RESPAWN,
    INIT_PACKET_ADAPTER,
    TERMINATE_FAILED_PACKET_ADAPTER,
    TERMINATE_PACKET_ADAPTER,
    CLOSE_UIS

}
