name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4.6.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build Bukkit
      run: ./gradlew bukkit:shadowJar

    - name: Publish Bukkit artifact
      uses: actions/upload-artifact@v4
      with:
        name: FlectonePulse-bukkit
        path: build/bukkit/libs
        if-no-files-found: warn

    - name: Build Velocity
      run: ./gradlew velocity:shadowJar

    - name: Publish Velocity artifact
      uses: actions/upload-artifact@v4
      with:
        name: FlectonePulse-velocity
        path: build/velocity/libs
        if-no-files-found: warn

    - name: Build Bungeecord
      run: ./gradlew bungeecord:shadowJar

    - name: Publish Bungeecord artifact
      uses: actions/upload-artifact@v4
      with:
        name: FlectonePulse-bungeecord
        path: build/bungeecord/libs
        if-no-files-found: warn


