name: Java CI and Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: bash ./gradlew clean fabricRemapJar bukkitMergeJars

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: FlectonePulse
          path: build/libs
          if-no-files-found: warn

      - name: Publish to Maven Central
        run: bash ./gradlew publishToMavenCentral
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
          SIGNING_KEY: ${{ secrets.GPG_PRIVATE_KEY }}